#!/usr/local/bin/zsh
brew update
brew upgrade
brew reinstall --HEAD --with-release neovim
pyenv activate neovim2
pip install --upgrade neovim
pyenv activate neovim3
pip install --upgrade neovim
pyenv deactivate
